version: '2'

services:

  gaia-mock:
    image: registry.pepinie.re:5000/gaia-mock:1.0.0
    volumes:
      - ./provisioning/docker/gaia-mock/nginx.subconf:/etc/nginx/sites-enabled/application.subconf:ro
      - ./provisioning/docker/gaia-mock/users.json:/users/users.json
      - ./provisioning/docker/gaia-mock/applications.json:/data/applications.json
    ports:
      - 8000:443

  nginx:
    image: nginx
    volumes:
      - ./provisioning/docker/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - 80:80
    depends_on:
<% if (clientRequired) { %>
      - client
<% } %>
<% if (serverRequired) { %>
      - server
<% } %>

<% if (clientRequired) { %>
  client:
    build: .
    volumes:
      - .:/code
    command: npm run client:watch -- --host 0.0.0.0
    ports:
      - 35729:35729
<% } %>

<% if (serverRequired) { %>
  server:
    build: .
    volumes:
      - .:/code
#    depends_on:
#      - postgresql
#      - mongodb
#      - elasticsearch
    command: npm run server:watch

###
# Postgresql configuration
###
#
#  postgresql:
#    image: postgres
#    environment:
#      - POSTGRES_USER=<%= applicationFolder %>
#      - POSTGRES_PASSWORD=<%= applicationFolder %>
#      - POSTGRES_DB=<%= applicationFolder %>
#
###

###
# Mongodb configuration
###
#
#  mongodb:
#    image: mongo
#
###

###
# Elasticsearch configuration
###
#
#  elasticsearch:
#    image: elasticsearch
#
###
<% } %>
